---
paths:
  github_web: 'https://github.com/ga4gh-schemablocks'
  src:
    - repository: blocks
      dir: schemas
    - repository: playground
      dir: schemas
  out_dirnames:
    json: json
    markdown: doc
    examples: examples
  out_web:
    - org: 'ga4gh-schemablocks'
      repository: 'ga4gh-schemablocks.github.io'
      dirs:
        jekyll: 'pages/_schemas/ga4gh'
        schemas: 'schemas/ga4gh'
        link: 'schemas/ga4gh'
generator_prefix: '+generated__'
jekyll_excerpt_separator: "<!--more-->"
prefix_expansions:
  orcid: 'https://orcid.org/'
  PMID: 'https://www.ncbi.nlm.nih.gov/pubmed/'
links:
  sb_status_levels: "https://schemablocks.org/about/sb-status-levels.html"
