---
github_organisation: ga4gh-schemablocks
site_domain_name: schemablocks.org
url: 'https://schemablocks.org'
tags:
  - code
  - specification
categories:
  - schemas
  - howto
tools_repo: tools
status_levels:
  - playground
  - community
  - proposed
  - implemented
  - core
schema_repos: # project directories on the same level as the `tools` repo
  - project_dir: blocks
    schema_dirs:
      - schemas
  - project_dir: playground
    schema_dirs:
      - schemas
    target_doc_dirname: playground
  - project_dir: template
    schema_dirs:
      - schemas
  - project_dir: sb-phenopackets
    schema_dirs:
      - schemas
  - project_dir: sb-checksum
    schema_dirs:
      - schemas
  - project_dir: sb-vr-spec
    schema_dirs:
      - schemas
  - project_dir: sb-beacon-api
    schema_dirs:
      - schemas
  - project_dir: sb-duo
    schema_dirs:
      - schemas
  - project_dir: sb-discovery-search
    schema_dirs:
      - schemas
#    - working
out_dirnames:
  json: generated/json
  markdown: generated/doc
  examples: generated/examples
webdocs:
  repo: 'ga4gh-schemablocks.github.io'
  jekylldir: 'pages/_schemas'
  schemadir: 'schemas'
  web_schemas_rel: "/schemas"
  web_html_rel: "/schemas"
generator_prefix: '+generated__'
schema_disclaimer: |
  <div id="schema-footer">
  This schema representation is for information purposes. The authorative 
  version remains with the developing project (see "provenance").
  </div>
jekyll_excerpt_separator: "<!--more-->"
prefix_expansions:
  orcid: 'https://orcid.org/'
  PMID: 'https://www.ncbi.nlm.nih.gov/pubmed/'
links:
  sb_status_levels: "https://schemablocks.org/about/sb-status-levels.html"
