---
github_organisation: ga4gh-schemablocks
site_domain_name: schemablocks.org
url: 'https://schemablocks.org'
tools_repo: tools
tags:
  - code
  - specification
categories:
  - schemas
  - howto
schema_repos:
  blocks:
    schema_dirs:
      - schemas
  playground:
    schema_dirs:
      - schemas
    target_doc_dirname: playground
  template:
    schema_dirs:
      - schemas
  sb-phenopackets:
    schema_dirs:
      - schemas
  sb-checksum:
    schema_dirs:
      - schemas
  sb-vr-spec:
    schema_dirs:
      - schemas
  sb-beacon-api:
    schema_dirs:
      - schemas
  sb-duo:
    schema_dirs:
      - schemas
  sb-discovery-search:
    schema_dirs:
      - schemas
#    - working
out_dirnames:
  json: generated/json
  markdown: generated/doc
  examples: generated/examples
webdocs:
  repo: 'ga4gh-schemablocks.github.io'
  jekylldir: 'pages/_schemas'
  schemadir: 'schemas'
  web_schemas_rel: "/schemas"
  web_html_rel: "/schemas"
generator_prefix: '+generated__'
schema_disclaimer: |
  <div id="schema-footer">
  This schema representation is for information purposes. The authorative 
  version remains with the developing project (see "provenance").
  </div>
jekyll_excerpt_separator: "<!--more-->"
prefix_expansions:
  orcid: 'https://orcid.org/'
  PMID: 'https://www.ncbi.nlm.nih.gov/pubmed/'
links:
  sb_status_levels: "https://schemablocks.org/about/sb-status-levels.html"
podmd: 'tools/podMD/podmd.pl'
