version: 2020-05-14
project: ''
# if predefined paths -> relative to script!
outdir: ''
schemafile: ''
headerfile: ''
# `__schema__` is inserted for each during parsing; other values can be defined
header:
  "$schema": http://json-schema.org/draft-07/schema#
  "$id": https://schemablocks.org/schemas/__project__/__schema__/__version__
  meta:
    contributors:
      - description: __contributor_name__
        id: __contributor_ORCID__
    provenance:
      - description: __project__
        id: __URI__
    used_by:
      - description: __project__
        id: __URI__
    sb_status: playground
